//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.InServices.ProxyToJobWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyToJobWebService.JobWebServiceSoap")]
    public interface JobWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOurCatalogue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Job.InServices.ProxyToJobWebService.MusicType[] GetOurCatalogue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOurCatalogue", ReplyAction="*")]
        System.Threading.Tasks.Task<Job.InServices.ProxyToJobWebService.MusicType[]> GetOurCatalogueAsync();
        
        // CODEGEN: Generating message contract since message GetOurCatalogueByAuthenticatingRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOurCatalogueByAuthenticating", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingResponse GetOurCatalogueByAuthenticating(Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOurCatalogueByAuthenticating", ReplyAction="*")]
        System.Threading.Tasks.Task<Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingResponse> GetOurCatalogueByAuthenticatingAsync(Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCatalogue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Job.InServices.ProxyToJobWebService.MusicType[] GetCatalogue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCatalogue", ReplyAction="*")]
        System.Threading.Tasks.Task<Job.InServices.ProxyToJobWebService.MusicType[]> GetCatalogueAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MusicType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string styleField;
        
        private Album[] albumsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
                this.RaisePropertyChanged("Style");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Album[] Albums {
            get {
                return this.albumsField;
            }
            set {
                this.albumsField = value;
                this.RaisePropertyChanged("Albums");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Album : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private string bandField;
        
        private double costField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Band {
            get {
                return this.bandField;
            }
            set {
                this.bandField = value;
                this.RaisePropertyChanged("Band");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("Cost");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeaderLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOurCatalogueByAuthenticating", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOurCatalogueByAuthenticatingRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Job.InServices.ProxyToJobWebService.HeaderLogin HeaderLogin;
        
        public GetOurCatalogueByAuthenticatingRequest() {
        }
        
        public GetOurCatalogueByAuthenticatingRequest(Job.InServices.ProxyToJobWebService.HeaderLogin HeaderLogin) {
            this.HeaderLogin = HeaderLogin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOurCatalogueByAuthenticatingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOurCatalogueByAuthenticatingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Job.InServices.ProxyToJobWebService.MusicType[] GetOurCatalogueByAuthenticatingResult;
        
        public GetOurCatalogueByAuthenticatingResponse() {
        }
        
        public GetOurCatalogueByAuthenticatingResponse(Job.InServices.ProxyToJobWebService.MusicType[] GetOurCatalogueByAuthenticatingResult) {
            this.GetOurCatalogueByAuthenticatingResult = GetOurCatalogueByAuthenticatingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JobWebServiceSoapChannel : Job.InServices.ProxyToJobWebService.JobWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobWebServiceSoapClient : System.ServiceModel.ClientBase<Job.InServices.ProxyToJobWebService.JobWebServiceSoap>, Job.InServices.ProxyToJobWebService.JobWebServiceSoap {
        
        public JobWebServiceSoapClient() {
        }
        
        public JobWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Job.InServices.ProxyToJobWebService.MusicType[] GetOurCatalogue() {
            return base.Channel.GetOurCatalogue();
        }
        
        public System.Threading.Tasks.Task<Job.InServices.ProxyToJobWebService.MusicType[]> GetOurCatalogueAsync() {
            return base.Channel.GetOurCatalogueAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingResponse Job.InServices.ProxyToJobWebService.JobWebServiceSoap.GetOurCatalogueByAuthenticating(Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingRequest request) {
            return base.Channel.GetOurCatalogueByAuthenticating(request);
        }
        
        public Job.InServices.ProxyToJobWebService.MusicType[] GetOurCatalogueByAuthenticating(Job.InServices.ProxyToJobWebService.HeaderLogin HeaderLogin) {
            Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingRequest inValue = new Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingRequest();
            inValue.HeaderLogin = HeaderLogin;
            Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingResponse retVal = ((Job.InServices.ProxyToJobWebService.JobWebServiceSoap)(this)).GetOurCatalogueByAuthenticating(inValue);
            return retVal.GetOurCatalogueByAuthenticatingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingResponse> Job.InServices.ProxyToJobWebService.JobWebServiceSoap.GetOurCatalogueByAuthenticatingAsync(Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingRequest request) {
            return base.Channel.GetOurCatalogueByAuthenticatingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingResponse> GetOurCatalogueByAuthenticatingAsync(Job.InServices.ProxyToJobWebService.HeaderLogin HeaderLogin) {
            Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingRequest inValue = new Job.InServices.ProxyToJobWebService.GetOurCatalogueByAuthenticatingRequest();
            inValue.HeaderLogin = HeaderLogin;
            return ((Job.InServices.ProxyToJobWebService.JobWebServiceSoap)(this)).GetOurCatalogueByAuthenticatingAsync(inValue);
        }
        
        public Job.InServices.ProxyToJobWebService.MusicType[] GetCatalogue() {
            return base.Channel.GetCatalogue();
        }
        
        public System.Threading.Tasks.Task<Job.InServices.ProxyToJobWebService.MusicType[]> GetCatalogueAsync() {
            return base.Channel.GetCatalogueAsync();
        }
    }
}
